version: '2'
services:
  web:
    image: php:7.1-apache
    working_dir: /var/www/html
    volumes: 
      - ./:/var/www/html/
      - ./config/php.ini:/etc/php7/apache2/conf.d/php.ini
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    #environment:
    #  - 
    ports:
      - "80:80"
      - "443:443"